Resources:
  BastionPolicyRoute53:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: Allow change route53 record sets
      ManagedPolicyName: bastion-policy-route53
      PolicyDocument:
        Statement:
          - Action:
              - route53:ListHostedZones
              - route53:ListHostedZonesByName
            Effect: Allow
            Resource: "*"
          - Action: route53:GetChange
            Effect: Allow
            Resource: "arn:aws:route53:::change/*"
          - Action:
              - route53:ListResourceRecordSets
              - route53:ChangeResourceRecordSets
            Effect: Allow
            Resource: !Sub
              - "arn:aws:route53:::hostedzone/${PublicZoneId}"
              - PublicZoneId: !Ref NurimbaPublicRoute
        Version: '2012-10-17'

  BastionPolicyS3:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: Get S3 objects
      ManagedPolicyName: bastion-policy-s3
      PolicyDocument:
        Statement:
          - Action: s3:GetObject
            Effect: Allow
            Resource: arn:aws:s3:::*/*
        Version: '2012-10-17'

  BastionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
        Version: '2008-10-17'
      ManagedPolicyArns:
        - !Ref BastionPolicyS3
        - !Ref BastionPolicyRoute53
      RoleName: bastion-role

  BastionProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref BastionRole
