service: nurimba-cloudformation
frameworkVersion: ^2.64.1
configValidationMode: error
variablesResolutionMode: 20210326

provider:
  name: aws
  region: us-east-1
  deploymentBucket:
    name: nurimba-serverless

resources:
  - ${file(./route53.yml)}
  - ${file(./iam.yml)}
  - ${file(./acm.yml)}
  - ${file(./vpc.yml)}
  - ${file(./bastion.yml)}
